# Generated by Django 3.2.9 on 2021-11-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Movie Name')),
                ('description', models.TextField(verbose_name='Movie Description')),
                ('likes', models.IntegerField(default=0, null=True)),
                ('watch_count', models.IntegerField(default=0, null=True)),
                ('rate', models.PositiveIntegerField(default=0, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('poster', models.ImageField(upload_to='movie/images')),
                ('video', models.FileField(upload_to='movie/videos')),
            ],
        ),
    ]
