# Generated by Django 3.2.9 on 2021-11-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211107_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_code', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.moviecode'),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
